# Generated by Django 5.0.1 on 2024-06-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_tv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='vote_count',
        ),
        migrations.AddField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
