# Generated by Django 5.0.1 on 2024-06-04 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_tv', '0003_alter_vote_created_at'),
        ('profiles', '0002_alter_profile_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ManyToManyField(related_name='lists', to='movie_tv.movie')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='profiles.profile')),
            ],
        ),
    ]
